#!/usr/bin/env python3
"""
Generate comprehensive PDF audit report for GED-ISIPA Master's thesis Chapter 3.
Uses: ReportLab (body) + HTML/Playwright (cover) + pypdf (merge)
"""

import os
import sys
import subprocess
import hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, CondPageBreak, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Color Palette (auto-generated by pdf.py palette.cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#efefed')
CARD_BG       = colors.HexColor('#eae9e7')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#5a5138')
COVER_BLOCK   = colors.HexColor('#736949')
BORDER        = colors.HexColor('#bbb7ab')
ICON          = colors.HexColor('#988447')
ACCENT        = colors.HexColor('#4b2ca9')
ACCENT_2      = colors.HexColor('#35c67d')
TEXT_PRIMARY   = colors.HexColor('#1c1b19')
TEXT_MUTED     = colors.HexColor('#797770')
SEM_SUCCESS   = colors.HexColor('#4b8a60')
SEM_WARNING   = colors.HexColor('#aa8c50')
SEM_ERROR     = colors.HexColor('#8a4741')
SEM_INFO      = colors.HexColor('#4c6680')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ━━ Paths ━━
OUTPUT_DIR = '/home/z/my-project/download'
BODY_PDF = os.path.join(OUTPUT_DIR, '_audit_body.pdf')
COVER_HTML = os.path.join(OUTPUT_DIR, '_audit_cover.html')
COVER_PDF = os.path.join(OUTPUT_DIR, '_audit_cover.pdf')
FINAL_PDF = os.path.join(OUTPUT_DIR, 'Audit_Academique_Chapitre3_GED-ISIPA.pdf')
PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'

# ━━ Page geometry ━━
PAGE_W, PAGE_H = A4  # 595.28 x 841.89
LEFT_MARGIN = 1.8 * cm
RIGHT_MARGIN = 1.8 * cm
TOP_MARGIN = 2.0 * cm
BOTTOM_MARGIN = 2.0 * cm
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ━━ Fonts ━━
# Use Liberation fonts (Times-compatible) and DejaVu
pdfmetrics.registerFont(TTFont('LibSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LibSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('LibSerif-Italic', '/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf'))
pdfmetrics.registerFont(TTFont('LibSans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LibSans-Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
registerFontFamily('LibSerif', normal='LibSerif', bold='LibSerif-Bold', italic='LibSerif-Italic')
registerFontFamily('LibSans', normal='LibSans', bold='LibSans-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')


# ━━ Styles ━━
styles = getSampleStyleSheet()

sH1 = ParagraphStyle(
    'H1Audit', fontName='LibSerif', fontSize=18, leading=24,
    textColor=ACCENT, spaceBefore=18, spaceAfter=10, alignment=TA_LEFT
)
sH2 = ParagraphStyle(
    'H2Audit', fontName='LibSerif', fontSize=14, leading=20,
    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=8, alignment=TA_LEFT
)
sH3 = ParagraphStyle(
    'H3Audit', fontName='LibSerif', fontSize=12, leading=17,
    textColor=COVER_BLOCK, spaceBefore=10, spaceAfter=6, alignment=TA_LEFT
)
sBody = ParagraphStyle(
    'BodyAudit', fontName='LibSerif', fontSize=10.5, leading=16,
    textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=6, alignment=TA_JUSTIFY,
    firstLineIndent=0
)
sBodyIndent = ParagraphStyle(
    'BodyIndent', parent=sBody, leftIndent=18
)
sBullet = ParagraphStyle(
    'BulletAudit', parent=sBody, leftIndent=24, bulletIndent=12,
    spaceBefore=2, spaceAfter=2
)
sSubBullet = ParagraphStyle(
    'SubBulletAudit', parent=sBody, leftIndent=40, bulletIndent=28,
    spaceBefore=1, spaceAfter=1
)
sTableHeader = ParagraphStyle(
    'TableHeaderAudit', fontName='LibSerif', fontSize=9.5, leading=13,
    textColor=colors.white, alignment=TA_CENTER
)
sTableCell = ParagraphStyle(
    'TableCellAudit', fontName='LibSerif', fontSize=9, leading=12,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT
)
sTableCellC = ParagraphStyle(
    'TableCellCenter', parent=sTableCell, alignment=TA_CENTER
)
sCaption = ParagraphStyle(
    'CaptionAudit', fontName='LibSerif', fontSize=9, leading=13,
    textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=3, spaceAfter=6
)
sTOCTitle = ParagraphStyle(
    'TOCTitle', fontName='LibSerif', fontSize=20, leading=28,
    textColor=ACCENT, spaceBefore=12, spaceAfter=18, alignment=TA_LEFT
)
sTOC1 = ParagraphStyle(
    'TOC1', fontName='LibSerif', fontSize=12, leftIndent=20,
    spaceBefore=6, spaceAfter=3, textColor=TEXT_PRIMARY
)
sTOC2 = ParagraphStyle(
    'TOC2', fontName='LibSerif', fontSize=10.5, leftIndent=40,
    spaceBefore=2, spaceAfter=2, textColor=TEXT_MUTED
)
sCallout = ParagraphStyle(
    'CalloutAudit', parent=sBody, fontSize=10, leading=15,
    leftIndent=12, borderPadding=6, spaceBefore=6, spaceAfter=6,
    backColor=CARD_BG, borderColor=ACCENT, borderWidth=1,
    borderPadding_left=10
)
sImpactCritique = ParagraphStyle(
    'ImpactCritique', parent=sBody, fontSize=10, leading=14,
    textColor=SEM_ERROR, fontName='LibSerif', leftIndent=18,
    spaceBefore=2, spaceAfter=4
)
sImpactEleve = ParagraphStyle(
    'ImpactEleve', parent=sBody, fontSize=10, leading=14,
    textColor=SEM_WARNING, fontName='LibSerif', leftIndent=18,
    spaceBefore=2, spaceAfter=4
)
sFooter = ParagraphStyle(
    'FooterAudit', fontName='LibSerif', fontSize=8, leading=10,
    textColor=TEXT_MUTED, alignment=TA_CENTER
)


# ━━ TOC-aware DocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


H1_ORPHAN_THRESHOLD = (PAGE_H - TOP_MARGIN - BOTTOM_MARGIN) * 0.15

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]


def make_table(data, col_widths, caption_text=None):
    """Create a styled table with optional caption."""
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    elements = [Spacer(1, 12), t]
    if caption_text:
        elements.append(Paragraph(caption_text, sCaption))
    elements.append(Spacer(1, 12))
    return elements


def p(text, style=sBody):
    return Paragraph(text, style)


def bullet(text, style=sBullet):
    return Paragraph('<bullet>&bull;</bullet> ' + text, style)


def sub_bullet(text):
    return Paragraph('<bullet>-</bullet> ' + text, sSubBullet)


# ━━ COVER HTML ━━
def write_cover_html():
    html = '''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800;900&family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
<style>
@page { size: 794px 1123px; margin: 0; }
html, body { margin: 0; padding: 0; width: 794px; height: 1123px; background: #fafaf8; overflow: hidden; }
.cover { position: absolute; inset: 0; width: 794px; height: 1123px; }
.layer-bg { position: absolute; inset: 0; z-index: 1; overflow: hidden; }
.grid-line { position: absolute; background: #5a5138; opacity: 0.03; }
.layer-struct { position: absolute; inset: 0; z-index: 2; }
.vline { position: absolute; left: 95px; top: 100px; width: 6px; height: 923px; background: #4b2ca9; border-radius: 3px; }
.hline-meta { position: absolute; left: 130px; top: 710px; width: 280px; height: 1px; background: #5a5138; opacity: 0.4; }
.layer-content { position: absolute; inset: 0; z-index: 3; }
.kicker { position: absolute; left: 130px; top: 130px; font-family: 'Inter', sans-serif; font-size: 16px; font-weight: 400; letter-spacing: 3px; color: #797770; text-transform: uppercase; }
.title { position: absolute; left: 130px; top: 240px; width: 580px; font-family: 'Inter', sans-serif; font-size: 42px; font-weight: 900; line-height: 1.15; color: #1c1b19; }
.title .accent { color: #4b2ca9; }
.summary { position: absolute; left: 130px; top: 490px; width: 440px; font-family: 'Inter', sans-serif; font-size: 16px; font-weight: 400; line-height: 1.6; color: #5a5138; opacity: 0.85; }
.meta { position: absolute; left: 130px; top: 730px; font-family: 'Inter', sans-serif; font-size: 15px; font-weight: 400; line-height: 2.0; color: #1c1b19; }
.footer { position: absolute; left: 130px; top: 970px; font-family: 'Inter', sans-serif; font-size: 13px; font-weight: 400; letter-spacing: 1.5px; color: #797770; text-transform: uppercase; }
.badge { display: inline-block; background: #8a4741; color: white; font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 3px; letter-spacing: 1px; margin-left: 10px; vertical-align: middle; }
</style>
</head>
<body>
<div class="cover">
  <div class="layer-bg">
    <!-- Grid pattern -->
    <div class="grid-line" style="left:0;top:200px;width:794px;height:1px;"></div>
    <div class="grid-line" style="left:0;top:400px;width:794px;height:1px;"></div>
    <div class="grid-line" style="left:0;top:600px;width:794px;height:1px;"></div>
    <div class="grid-line" style="left:0;top:800px;width:794px;height:1px;"></div>
    <div class="grid-line" style="left:200px;top:0;width:1px;height:1123px;"></div>
    <div class="grid-line" style="left:400px;top:0;width:1px;height:1123px;"></div>
    <div class="grid-line" style="left:600px;top:0;width:1px;height:1123px;"></div>
  </div>
  <div class="layer-struct">
    <div class="vline"></div>
    <div class="hline-meta"></div>
  </div>
  <div class="layer-content">
    <div class="kicker">RAPPORT D'AUDIT ACADEMIQUE</div>
    <div class="title">
      Chapitre III<br>
      <span class="accent">Implementation</span> &mdash; GED-ISIPA<br>
      <span style="font-size:24px;font-weight:400;color:#797770;">Audit de conformite entre le memoire<br>et l'application reellement deployee</span>
    </div>
    <div class="summary">
      Ce rapport identifie 12 ecarts majeurs et 18 ecarts mineurs entre les descriptions du Chapitre 3 du memoire et le code reellement deploye. Le taux de completude estime est de 45%. Le chapitre necessite des revisions majeures avant la soutenance.
    </div>
    <div class="meta">
      Master en Informatique de Gestion<br>
      Institut Superieur Informatique Programmation & Administration<br>
      Annee academique 2024-2025
    </div>
    <div class="footer">
      Document confidentiel <span class="badge">12 ECARTS CRITIQUES</span>
    </div>
  </div>
</div>
</body>
</html>'''
    with open(COVER_HTML, 'w', encoding='utf-8') as f:
        f.write(html)


# ━━ PAGE TEMPLATE WITH HEADER/FOOTER ━━
def header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont('LibSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_MARGIN, PAGE_H - TOP_MARGIN + 10,
                      "Rapport d'Audit Academique - Chapitre III - GED-ISIPA")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, PAGE_H - TOP_MARGIN + 6, PAGE_W - RIGHT_MARGIN, PAGE_H - TOP_MARGIN + 6)
    # Footer
    canvas.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 14, "Confidentiel - Audit de conformite")
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 14, f"Page {doc.page}")
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 4, PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 4)
    canvas.restoreState()


def header_footer_toc(canvas, doc):
    canvas.saveState()
    canvas.setFont('LibSerif', 8)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_MARGIN, PAGE_H - TOP_MARGIN + 10,
                      "Rapport d'Audit Academique - Chapitre III - GED-ISIPA")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, PAGE_H - TOP_MARGIN + 6, PAGE_W - RIGHT_MARGIN, PAGE_H - TOP_MARGIN + 6)
    canvas.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 14, "Table des matieres")
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 14, f"Page {doc.page}")
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 4, PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 4)
    canvas.restoreState()


# ━━ BUILD STORY ━━
def build_story():
    story = []

    # ── TABLE OF CONTENTS ──
    toc = TableOfContents()
    toc.levelStyles = [sTOC1, sTOC2]
    story.append(Paragraph("<b>TABLE DES MATIERES</b>", sTOCTitle))
    story.append(Spacer(1, 12))
    story.append(toc)
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════════════
    # SECTION 1 - SYNTHESE EXECUTIVE
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>1. SYNTHESE EXECUTIVE</b>", sH1))

    story.append(p(
        "Le present rapport constitue un audit approfondi de conformite entre le Chapitre III du memoire "
        "de Master intitule <b>Impl&eacute;mentation</b> dans le cadre du projet GED-ISIPA et l'application "
        "reellement deployee. Cet audit a ete realise par analyse systematique du code source, comparaison "
        "avec les descriptions du memoire, et verification des fonctionnalites annoncees versus celles "
        "effectivement implementees. Les resultats revelent un ecart significatif entre la documentation "
        "academique et la realite technique du produit, soulevant des preoccupations serieuses quant a "
        "la fiabilite des informations presentees dans le memoire."
    ))
    story.append(p(
        "L'audit a identifie un total de <b>30 ecarts</b> entre les descriptions du Chapitre 3 et "
        "l'application reelle, dont 12 ecarts majeurs de nature critique ou elevee et 18 ecarts mineurs. "
        "Ces ecarts couvrent des domaines fondamentaux tels que la securite (hachage des mots de passe), "
        "l'architecture (mono-tenant vs multi-tenant SaaS), le controle d'acces (5 roles vs 14 roles), "
        "et les resultats de tests (fabriques plutot que mesures). Le taux de completude global du chapitre "
        "est estime a <b>45%</b>, ce qui signifie que plus de la moitie des informations presentees sont "
        "inexactes, incompletes ou trompeuses."
    ))

    # Key metrics table
    metrics_data = [
        [Paragraph('<b>Indicateur</b>', sTableHeader),
         Paragraph('<b>Valeur</b>', sTableHeader),
         Paragraph('<b>Appreciation</b>', sTableHeader)],
        [Paragraph('Taux de completude', sTableCell),
         Paragraph('45%', sTableCellC),
         Paragraph('<font color="#8a4741">Insuffisant</font>', sTableCellC)],
        [Paragraph('Ecarts majeurs identifie', sTableCell),
         Paragraph('12', sTableCellC),
         Paragraph('<font color="#8a4741">Critique</font>', sTableCellC)],
        [Paragraph('Ecarts mineurs identifie', sTableCell),
         Paragraph('18', sTableCellC),
         Paragraph('<font color="#aa8c50">Attention</font>', sTableCellC)],
        [Paragraph('Fonctionnalites non documentees', sTableCell),
         Paragraph('16+', sTableCellC),
         Paragraph('<font color="#8a4741">Critique</font>', sTableCellC)],
        [Paragraph('Sections incompletes', sTableCell),
         Paragraph('4', sTableCellC),
         Paragraph('<font color="#aa8c50">Eleve</font>', sTableCellC)],
        [Paragraph('Schema manquants', sTableCell),
         Paragraph('8', sTableCellC),
         Paragraph('<font color="#aa8c50">Eleve</font>', sTableCellC)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.35]
    story.extend(make_table(metrics_data, col_w, "Tableau 1.1 - Indicateurs cles de l'audit"))

    story.append(Spacer(1, 12))
    story.append(p(
        "<b>Verdict : Le chapitre necessite des revisions MAJEURES avant soutenance.</b> "
        "Les ecarts identifies sont d'une ampleur telle qu'ils pourraient soulever des questions "
        "fondamentales lors de la defense, notamment sur l'integrite academique des resultats presentes "
        "et la fiabilite des descriptions techniques. Il est imperatif de corriger les informations "
        "inexactes, completer les sections manquantes, et ajouter les elements de preuve (captures d'ecran, "
        "resultats de tests reels) avant la soutenance."
    ))

    # ════════════════════════════════════════════════════════════════
    # SECTION 2 - ECARTS CRITIQUES
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>2. ECARTS CRITIQUES</b>", sH1))
    story.append(p(
        "Cette section detaille les 12 ecarts majeurs identifies lors de l'audit. Chaque ecart est "
        "presente avec sa description, les elements de preuve, et une evaluation de son impact sur la "
        "credibilite du memoire. Ces ecarts representent des informations inexactes ou obsolete presentes "
        "dans le Chapitre 3, qui contredisent directement le code reellement deploye."
    ))

    # 2.1 RBAC
    story.append(add_heading("<b>2.1 Systeme RBAC decrit vs reel</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit un systeme de controle d'acces base sur 5 roles : ADMIN, DIRECTOR, "
        "SECRETARY, ARCHIVIST et VIEWER. Cette description est presentee comme exhaustive et constitue "
        "la base de la matrice RBAC du Tableau 3.9 du memoire. Or, l'application reellement deployee "
        "implemente un systeme bien plus complexe comprenant 14 roles distincts, refletant une architecture "
        "multi-tenant SaaS qui n'est pas documentee dans le chapitre."
    ))
    story.append(p(
        "Les 14 roles reels sont : SUPER_ADMIN, ORG_ADMIN, MANAGER, USER, VIEWER, DEAN, PROFESSOR, "
        "DOCTOR, NURSE, LAWYER, PARALEGAL, CFO, HR_MANAGER et CIVIL_SERVANT. Ces roles specialises "
        "sont directement lies aux differents types d'organisations supportees par la plateforme "
        "(universites, hopitaux, cabinets juridiques, etc.), ce qui revele une fonctionnalite majeure "
        "non documentee."
    ))

    rbac_data = [
        [Paragraph('<b>Aspect</b>', sTableHeader),
         Paragraph('<b>Chapitre 3</b>', sTableHeader),
         Paragraph('<b>Application reelle</b>', sTableHeader)],
        [Paragraph('Nombre de roles', sTableCell),
         Paragraph('5', sTableCellC),
         Paragraph('14', sTableCellC)],
        [Paragraph('Roles decrits', sTableCell),
         Paragraph('ADMIN, DIRECTOR, SECRETARY, ARCHIVIST, VIEWER', sTableCell),
         Paragraph('SUPER_ADMIN, ORG_ADMIN, MANAGER, USER, VIEWER, DEAN, PROFESSOR, DOCTOR, NURSE, LAWYER, PARALEGAL, CFO, HR_MANAGER, CIVIL_SERVANT', sTableCell)],
        [Paragraph('Granularite', sTableCell),
         Paragraph('Generique / mono-organisation', sTableCellC),
         Paragraph('Specialisee par type d\'organisation', sTableCellC)],
        [Paragraph('Matrice RBAC', sTableCell),
         Paragraph('Tableau 3.9 (5 roles)', sTableCellC),
         Paragraph('Entierement obsol&egrave;te', sTableCellC)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.20, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.45]
    story.extend(make_table(rbac_data, col_w, "Tableau 2.1 - Comparaison du systeme RBAC"))
    story.append(p(
        "<b>Impact : CRITIQUE</b> - La matrice RBAC (Tableau 3.9) est entierement obsolete et ne "
        "reflete en rien le systeme reellement implemente. Un membre du jury qui verifierait cette "
        "matrice decouvrirait immediatement l'incoherence.", sImpactCritique
    ))

    # 2.2 Architecture
    story.append(add_heading("<b>2.2 Architecture mono-tenant vs multi-tenant SaaS</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit un systeme mono-tenant concu exclusivement pour l'ISIPA, comme si "
        "l'application etait dediee a un seul etablissement. En realite, l'application est une plateforme "
        "SaaS multi-tenant capable d'heberger 8 types d'organisations differents : UNIVERSITY, HOSPITAL, "
        "COMPANY, GOVERNMENT, SME, INSTITUTION, NGO et LAW_FIRM. Cette difference architecturale "
        "fondamentale n'est absolument pas documentee et change completement la portee du projet."
    ))
    story.append(p(
        "Le modele de donnees reel inclut de nombreuses entites non documentees dans le MCD du Chapitre 3. "
        "Les modeles manquants incluent : Organization (gestion des tenants), OrganizationModule (activation "
        "des modules par organisation), Subscription (gestion des abonnements), Workflow (moteur de workflow "
        "configurable), WorkflowState (etats du workflow), WorkflowTransition (transitions entre etats), "
        "Notification (systeme de notifications), SystemSetting (parametres systeme) et AccessLog "
        "(journal d'acces). Ces entites sont essentielles au fonctionnement de la plateforme mais "
        "sont totalement absentes du modele conceptuel de donnees presente dans le memoire."
    ))
    story.append(p(
        "<b>Impact : CRITIQUE</b> - Le MCD/MLD/MPD presente dans le Chapitre 3 est incomplet et "
        "ne represente qu'une fraction du schema reel. Le modele decrit 5 entites alors que l'application "
        "en contient au moins 12, soit plus du double.", sImpactCritique
    ))

    # 2.3 bcrypt
    story.append(add_heading("<b>2.3 bcrypt non implemente</b>", sH2, level=1))
    story.append(p(
        "Cet ecart est sans doute le plus preoccupant du point de vue de l'integrite academique. "
        "Le Chapitre 3 affirme de maniere repetitive que le systeme utilise le <b>hachage bcrypt "
        "avec 12 salt rounds</b> pour la securisation des mots de passe. Cette affirmation est presentee "
        "comme une fonctionnalite implementee et testee, avec des resultats de performance mentionnant "
        "explicitement bcrypt. Cependant, l'analyse du code source revele une realite radicalement "
        "differente."
    ))
    story.append(p(
        "Dans le fichier <b>auth.ts a la ligne 69</b>, le code reel effectue la verification des "
        "identifiants par une simple comparaison en texte brut : <font name='DejaVuSans' size=9>"
        "user.password !== credentials.password</font>. Il n'y a aucune utilisation de bcrypt, "
        "aucun salt, aucun hachage. Les mots de passe sont stockes et compares en clair, ce qui "
        "represente une vulnerabilite de securite majeure. Affirmer l'utilisation de bcrypt alors "
        "que cette securite n'existe pas constitue une inexactitude grave qui pourrait etre qualifiee "
        "de tromperie si elle n'est pas corrigee."
    ))
    story.append(p(
        "<b>Impact : CRITIQUE</b> - Affirme une securite qui n'existe pas. Les mots de passe "
        "sont compares en texte brut, ce qui est inacceptable en production et constitue une "
        "fausse declaration dans le memoire.", sImpactCritique
    ))

    # 2.4 Donnees de seed
    story.append(add_heading("<b>2.4 Donnees de seed incorrectes</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 presente dans le Tableau 3.13 des identifiants de connexion pour les comptes "
        "de test, notamment admin@isipa.ac.cd avec le mot de passe Admin@2024. Ces informations "
        "sont incorrectes. L'application reelle utilise l'adresse admin@isipa.cd avec le mot de "
        "passe admin123, et possede en outre 8 autres comptes de test non mentionnes dans le memoire. "
        "Si un membre du jury tentait de verifier les identifiants du Tableau 3.13, il echouerait "
        "systematiquement, ce qui souleverait des questions sur la fiabilite de l'ensemble du document."
    ))
    seed_data = [
        [Paragraph('<b>Champ</b>', sTableHeader),
         Paragraph('<b>Chapitre 3</b>', sTableHeader),
         Paragraph('<b>Application reelle</b>', sTableHeader)],
        [Paragraph('Email admin', sTableCell),
         Paragraph('admin@isipa.ac.cd', sTableCell),
         Paragraph('admin@isipa.cd', sTableCell)],
        [Paragraph('Mot de passe admin', sTableCell),
         Paragraph('Admin@2024', sTableCell),
         Paragraph('admin123', sTableCell)],
        [Paragraph('Nombre de comptes', sTableCell),
         Paragraph('Non precise', sTableCellC),
         Paragraph('9 comptes de test', sTableCellC)],
        [Paragraph('Securite mots de passe', sTableCell),
         Paragraph('Haches (bcrypt)', sTableCellC),
         Paragraph('Texte brut', sTableCellC)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.40]
    story.extend(make_table(seed_data, col_w, "Tableau 2.4 - Comparaison des donnees de seed"))
    story.append(p(
        "<b>Impact : ELEVE</b> - Les identifiants du Tableau 3.13 sont faux et ne permettent "
        "pas la verification. De plus, le mot de passe admin123 en texte brut est une vulnerabilite "
        "de securite.", sImpactEleve
    ))

    # 2.5 Next.js
    story.append(add_heading("<b>2.5 Version Next.js incorrecte</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 indique utiliser Next.js 14 comme framework de developpement, tandis que "
        "l'application reelle utilise Next.js 16.2.6. Cette difference de version est significative "
        "car Next.js 16 introduit des changements majeurs notamment au niveau du compilateur "
        "(Turbopack), du systeme de routing, et des composants serveur. La documentation et les "
        "exemples de code presentes dans le memoire ne sont pas compatibles avec la version "
        "reellement utilisee, ce qui cree une confusion pour le lecteur qui souhaiterait reproduire "
        "ou verifier les implementations decrites."
    ))
    story.append(p(
        "<b>Impact : MODERE</b> - La version incorrecte du framework peut induire en erreur "
        "sur les capacites techniques et les patterns d'implementation utilises.", sImpactEleve
    ))

    # 2.6 Methodes HTTP
    story.append(add_heading("<b>2.6 Methodes HTTP incorrectes</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit l'utilisation de la methode PATCH pour les actions approve, publish, "
        "archive et restore sur les documents. En realite, l'application utilise la methode POST pour "
        "toutes ces actions. Cette difference, bien que technique, est significative car PATCH et POST "
        "ont des semantiques REST differentes : PATCH implique une modification partielle d'une ressource "
        "existante, tandis que POST est utilise pour declencher une action. L'utilisation systematique "
        "de POST suggere une conception orientee action plutot que ressource."
    ))
    story.append(p(
        "Par ailleurs, le Chapitre 3 omet plusieurs routes API critiques qui existent dans l'application : "
        "/api/documents/[id]/download et /api/upload pour la gestion des fichiers. Inversement, de "
        "nombreuses routes existantes ne sont pas documentees : /api/search, /api/billing, /api/modules, "
        "/api/notifications, /api/settings, /api/stats/platform, /api/organizations, "
        "/api/organizations/[id]/modules, /api/workflows, /api/workflows/[id]/execute. Ces routes "
        "non documentees revelent des fonctionnalites entieres absentes du memoire."
    ))
    routes_data = [
        [Paragraph('<b>Route</b>', sTableHeader),
         Paragraph('<b>Statut dans le Chapitre 3</b>', sTableHeader),
         Paragraph('<b>Existe reellement</b>', sTableHeader)],
        [Paragraph('/api/documents/[id]/download', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/upload', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/search', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/billing', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/modules', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/notifications', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/settings', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/stats/platform', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/organizations', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
        [Paragraph('/api/workflows', sTableCell),
         Paragraph('Absente', sTableCellC),
         Paragraph('Oui', sTableCellC)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.30]
    story.extend(make_table(routes_data, col_w, "Tableau 2.6 - Routes API non documentees"))
    story.append(p(
        "<b>Impact : ELEVE</b> - L'API documentee ne represente qu'une fraction de l'API reelle. "
        "Les methodes HTTP et les routes sont inexactes.", sImpactEleve
    ))

    # 2.7 Format reference
    story.append(add_heading("<b>2.7 Format de reference document incorrect</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 specifie un format de reference structur&eacute; pour les documents : "
        "ISIPA-XX-TYPE-AAAA-NNN (par exemple ISIPA-01-FAC-2024-001). Ce format suggere un systeme "
        "de referencing hierarchique et significatif, ou chaque composant de la reference porte une "
        "information semantique. En realite, l'application gen&egrave;re des references sous le format "
        "DOC-{timestamp}-{random}, qui est un identifiant purement technique sans signification "
        "semantique. Ce format ne permet pas d'identifier le type de document, l'annee, ou le "
        "departement a partir de la reference, contrairement a ce qui est affirme dans le memoire."
    ))
    story.append(p(
        "<b>Impact : MODERE</b> - Le systeme de referencing decrit est plus sophistique que celui "
        "implemente, ce qui reflete un ecart entre la conception theorique et la realite pratique.",
        sImpactEleve
    ))

    # 2.8 SHA-256
    story.append(add_heading("<b>2.8 SHA-256 non implemente</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 affirme que le systeme effectue une verification d'integrite des fichiers "
        "via un hachage SHA-256, permettant de detecter toute alteration des documents archives. "
        "Cette fonctionnalite est presentee comme un element cle de la fiabilite du systeme d'archivage. "
        "Cependant, l'analyse du code source ne revele aucune implementation de hachage SHA-256 ni "
        "aucune verification d'integrite. Aucune colonne de hash n'existe dans le modele de donnees, "
        "aucune fonction de calcul de hash n'est presente dans les services, et aucune verification "
        "n'est effectuee lors du telechargement ou de la consultation des documents."
    ))
    story.append(p(
        "<b>Impact : ELEVE</b> - Affirmer une fonctionnalite de verification d'integrite qui "
        "n'existe pas est une inexactitude serieuse, surtout dans un systeme de gestion electronique "
        "de documents ou l'integrite des archives est fondamentale.", sImpactEleve
    ))

    # 2.9 Zod
    story.append(add_heading("<b>2.9 Validation Zod non implementee</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 mentionne l'utilisation de la bibliotheque Zod pour la validation des entrees "
        "cote serveur, presentant cette validation comme une couche de securite essentielle contre "
        "les injections et les donnees malformees. En realite, aucune validation Zod n'est implementee "
        "dans les routes API de l'application. Les donnees sont acceptees telles quelles sans validation "
        "de schema, ce qui expose l'application a des vulnerabilites d'injection et de validation "
        "de donnees. Cette absence de validation est d'autant plus preoccupante qu'elle est combinee "
        "avec l'absence de hachage des mots de passe et la comparaison en texte brut."
    ))
    story.append(p(
        "<b>Impact : ELEVE</b> - L'absence de validation des entrees combinee a l'absence de "
        "hachage des mots de passe cree une surface d'attaque significative.", sImpactEleve
    ))

    # 2.10 Tests fabriques
    story.append(add_heading("<b>2.10 Resultats de tests fabriques</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 presente dans le Tableau 3.16 des resultats de tests qui sont manifestement "
        "theoriques et non mesures. Par exemple, le test de performance affirme que l'authentification "
        "prend 450ms avec bcrypt, alors que bcrypt n'est pas implemente dans l'application. Ce resultat "
        "est donc mathematiquement impossible et constitue une fabrication. De meme, le test TF-04 "
        "indique que l'application retourne un code 403 Forbidden pour un utilisateur non autorise, "
        "alors que l'application reelle retourne un code 401 Unauthorized ou procede a une redirection."
    ))
    story.append(p(
        "L'ensemble des resultats du Tableau 3.16 semble avoir ete construit theoriquement plutot "
        "que mesure reellement. Aucun framework de test automatise n'est present dans le projet, "
        "aucun script de test de charge n'existe, et aucune trace d'execution de tests ne peut etre "
        "verifiee. La presentation de resultats fabriques comme s'ils avaient ete mesures constitue "
        "un probleme d'integrite academique potentiel."
    ))
    story.append(p(
        "<b>Impact : CRITIQUE</b> - Les resultats de tests presentes sont fabriques et non mesures. "
        "Ceci souleve des questions serieuses sur l'integrite academique du travail.", sImpactCritique
    ))

    # 2.11 Middleware
    story.append(add_heading("<b>2.11 Middleware decrit vs proxy reel</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit l'utilisation d'un <b>middleware Next.js</b> standard pour la gestion "
        "de l'authentification et du routage. En realite, l'application utilise un fichier proxy.ts "
        "(renomm&eacute; pour etre compatible avec Next.js 16) qui fonctionne differemment du "
        "middleware traditionnel. Ce proxy implemente des fonctionnalites plus avancees que le "
        "middleware decrit, notamment le rate limiting (30 requetes/minute pour l'authentification, "
        "100 requetes/minute pour l'API generale) et la gestion multi-tenant des routes."
    ))
    story.append(p(
        "<b>Impact : MODERE</b> - La description du middleware est incomplete et ne reflete pas "
        "le mecanisme d'authentification et de routage reellement utilise.", sImpactEleve
    ))

    # 2.12 Dashboards
    story.append(add_heading("<b>2.12 Tableau de bord unique vs 6 dashboards</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit un seul tableau de bord administrateur, presentant des statistiques "
        "generales sur les documents et l'activite du systeme. En realite, l'application implemente "
        "<b>6 dashboards specialises</b> par type d'organisation (University, Hospital, Company, "
        "Government, SME, Law Firm), chacun avec des metriques, des graphiques et des fonctionnalites "
        "specifiques au secteur d'activite. S'y ajoute un dashboard Super Admin dedie a la gestion "
        "de la plateforme globale. Cette richesse fonctionnelle est entierement absente du memoire."
    ))
    dashboard_data = [
        [Paragraph('<b>Dashboard</b>', sTableHeader),
         Paragraph('<b>Dans le Chapitre 3</b>', sTableHeader),
         Paragraph('<b>Type d\'organisation</b>', sTableHeader)],
        [Paragraph('Universitaire', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('UNIVERSITY', sTableCellC)],
        [Paragraph('Hospitalier', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('HOSPITAL', sTableCellC)],
        [Paragraph('Entreprise', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('COMPANY', sTableCellC)],
        [Paragraph('Gouvernemental', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('GOVERNMENT', sTableCellC)],
        [Paragraph('PME', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('SME', sTableCellC)],
        [Paragraph('Cabinet juridique', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('LAW_FIRM', sTableCellC)],
        [Paragraph('Super Admin', sTableCell),
         Paragraph('Non documente', sTableCellC),
         Paragraph('Plateforme', sTableCellC)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.40]
    story.extend(make_table(dashboard_data, col_w, "Tableau 2.12 - Dashboards non documentes"))
    story.append(p(
        "<b>Impact : ELEVE</b> - L'application offre une experience utilisateur bien plus riche "
        "et specialisee que ce que le memoire decrit. Les dashboards specialises sont un atout "
        "majeur du projet qui merite d'etre documente.", sImpactEleve
    ))

    # ════════════════════════════════════════════════════════════════
    # SECTION 3 - FONCTIONNALITES NON DOCUMENTEES
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>3. FONCTIONNALITES EXISTANTES NON DOCUMENTEES</b>", sH1))
    story.append(p(
        "L'application GED-ISIPA deployee contient de nombreuses fonctionnalites avancees qui ne "
        "sont absolument pas mentionnees dans le Chapitre 3 du memoire. Ces fonctionnalites representent "
        "une valeur ajoutee significative du projet et leur absence de documentation est d'autant plus "
        "regrettable qu'elles demontreraient la maturite technique de l'implementation. Les fonctionnalites "
        "non documentees incluent notamment un systeme multi-tenant complet avec isolation des donnees "
        "par organisation, six dashboards specialises selon le type d'organisation, un panneau Super Admin "
        "avec gestion des organisations, des modules, des analyses et de la facturation, ainsi qu'un "
        "moteur de modules avec dependances inter-modulaires."
    ))
    story.append(p(
        "On egalement identifie un moteur de tokens AEIP generant des identifiants au format "
        "AEIP-{PREFIX}-{6CHARCODE}, un systeme de notifications, une page d'inscription et "
        "d'authentification, un theme sombre/clair avec basculement automatique, un mecanisme de "
        "rate limiting (30 requetes/minute pour l'authentification, 100 requetes/minute pour l'API "
        "generale), des statistiques plateforme via /api/stats/platform, une recherche globale via "
        "/api/search, un moteur de workflow configurable (et non fige a 5 etats), un systeme de "
        "gestion des abonnements, un systeme de parametres systeme, et un journal d'acces detaille."
    ))

    features = [
        ("Systeme multi-tenant avec organisation isolee", "Permet d'heberger plusieurs organisations sur une meme plateforme avec isolation des donnees"),
        ("6 dashboards specialises par type d'organisation", "Chaque type d'organisation beneficie d'un tableau de bord adapte a son secteur"),
        ("Panneau Super Admin", "Gestion complete de la plateforme : /admin/dashboard, /admin/organizations, /admin/modules, /admin/analytics, /admin/billing"),
        ("Moteur de modules (15 modules avec dependances)", "Systeme d'activation/desactivation de fonctionnalites par organisation"),
        ("Moteur de tokens AEIP (AEIP-{PREFIX}-{6CHARCODE})", "Generation d'identifiants uniques et tracesables pour les documents"),
        ("Systeme de notifications", "Alertes en temps reel pour les actions importantes"),
        ("Page d'inscription/registration", "Auto-enregistrement des utilisateurs et organisations"),
        ("Theme sombre/clair", "Interface adaptative avec basculement automatique"),
        ("Rate limiting", "Protection contre les abus : 30 req/min auth, 100 req/min API"),
        ("Statistiques plateforme (/api/stats/platform)", "Metriques globales d'utilisation de la plateforme"),
        ("Recherche globale (/api/search)", "Recherche full-text a travers tous les documents"),
        ("Moteur de workflow configurable", "Workflows dynamiques, non figes a 5 etats"),
        ("Gestion des abonnements (Subscription)", "Systeme de plans et de facturation"),
        ("Systeme de parametres (SystemSetting)", "Configuration dynamique de la plateforme"),
        ("Journal d'acces (AccessLog)", "Tracabilite complete des actions utilisateur"),
        ("Thème sombre/clair avec toggle", "Adaptation visuelle selon les preferences utilisateur"),
    ]

    feat_data = [
        [Paragraph('<b>N</b>', sTableHeader),
         Paragraph('<b>Fonctionnalite</b>', sTableHeader),
         Paragraph('<b>Description</b>', sTableHeader)]
    ]
    for i, (name, desc) in enumerate(features, 1):
        feat_data.append([
            Paragraph(str(i), sTableCellC),
            Paragraph(name, sTableCell),
            Paragraph(desc, sTableCell)
        ])
    col_w = [AVAILABLE_WIDTH * 0.06, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.59]
    story.extend(make_table(feat_data, col_w, "Tableau 3.1 - Fonctionnalites non documentees"))

    # ════════════════════════════════════════════════════════════════
    # SECTION 4 - SECTIONS INCOMPLETES
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>4. SECTIONS INCOMPLETES OU INSUFFISAMMENT DETAILLEES</b>", sH1))

    # 4.1 MCD
    story.append(add_heading("<b>4.1 MCD/MLD/MPD incomplets</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 ne decrit que 5 entites dans son modele conceptuel de donnees, tandis que "
        "l'application reelle en contient au moins 12. Les entites manquantes sont fondamentales pour "
        "comprendre l'architecture du systeme. Parmi les entites non documentees, on trouve Workflow "
        "et ses entites associees WorkflowState et WorkflowTransition, qui constituent le moteur de "
        "workflow configurable ; Organization et OrganizationModule, qui impl&eacute;mentent "
        "l'architecture multi-tenant ; Subscription, qui gere les abonnements ; Notification, qui "
        "impl&eacute;mente le systeme d'alertes ; SystemSetting, qui permet la configuration "
        "dynamique ; et AccessLog, qui assure la tracabilite. L'absence de ces entites dans le MCD "
        "rend la description du modele de donnees gravement incomplete et trompeuse."
    ))

    missing_entities = [
        [Paragraph('<b>Entite</b>', sTableHeader),
         Paragraph('<b>Role</b>', sTableHeader),
         Paragraph('<b>Cles</b>', sTableHeader)],
        [Paragraph('Organization', sTableCell),
         Paragraph('Gestion multi-tenant', sTableCell),
         Paragraph('type, name, slug, settings', sTableCell)],
        [Paragraph('OrganizationModule', sTableCell),
         Paragraph('Activation modules par org', sTableCell),
         Paragraph('organizationId, moduleId, isActive', sTableCell)],
        [Paragraph('Subscription', sTableCell),
         Paragraph('Gestion abonnements', sTableCell),
         Paragraph('organizationId, plan, status', sTableCell)],
        [Paragraph('Workflow', sTableCell),
         Paragraph('Moteur de workflow configurable', sTableCell),
         Paragraph('name, organizationTypeId', sTableCell)],
        [Paragraph('WorkflowState', sTableCell),
         Paragraph('Etats du workflow', sTableCell),
         Paragraph('workflowId, name, isInitial, isFinal', sTableCell)],
        [Paragraph('WorkflowTransition', sTableCell),
         Paragraph('Transitions entre etats', sTableCell),
         Paragraph('fromStateId, toStateId, requiredRole', sTableCell)],
        [Paragraph('Notification', sTableCell),
         Paragraph('Systeme de notifications', sTableCell),
         Paragraph('userId, type, message, read', sTableCell)],
        [Paragraph('SystemSetting', sTableCell),
         Paragraph('Parametres systeme', sTableCell),
         Paragraph('key, value, category', sTableCell)],
        [Paragraph('AccessLog', sTableCell),
         Paragraph('Journal d\'acces', sTableCell),
         Paragraph('userId, action, resource, timestamp', sTableCell)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.25, AVAILABLE_WIDTH * 0.35, AVAILABLE_WIDTH * 0.40]
    story.extend(make_table(missing_entities, col_w, "Tableau 4.1 - Entites manquantes dans le MCD"))

    # 4.2 Architecture
    story.append(add_heading("<b>4.2 Architecture technique incomplete</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 3 decrit l'architecture comme une <b>application monolithique simplifiee</b>, "
        "ce qui est incorrect. L'application est en realite une plateforme SaaS multi-tenant avec "
        "une architecture modulaire. La description monolithique omet les aspects fondamentaux de "
        "l'architecture reelle : le modele SaaS multi-tenant avec isolation des donnees par "
        "organisation, le moteur de modules qui permet d'activer ou desactiver des fonctionnalites "
        "par organisation avec gestion des dependances inter-modulaires, et le systeme de tokens "
        "AEIP qui genere des identifiants uniques tracesables. Ces composants architecturaux "
        "representent une complexite et une maturite technique significatives qui meritent d'etre "
        "documentees dans un memoire de Master."
    ))

    # 4.3 Environnement
    story.append(add_heading("<b>4.3 Environnement de development obsolescent</b>", sH2, level=1))
    story.append(p(
        "La description de l'environnement de development dans le Chapitre 3 est obsolete sur "
        "plusieurs points critiques. La version de Next.js est indiquee comme 14 alors que la version "
        "reelle est 16.2.6. Le compilateur Turbopack, qui est un changement majeur introduit dans "
        "les versions recentes de Next.js et qui impacte significativement les performances de "
        "developpement, n'est pas mentionne. De meme, Tailwind CSS 4, qui apporte des changements "
        "importants dans la gestion des styles, et Prisma v6, qui introduit des ameliorations "
        "significatives dans l'ORM, ne sont pas mentionnes. Ces omissions donnent une image "
        "incomplete et outdated de la stack technique reelle."
    ))

    # 4.4 Tests
    story.append(add_heading("<b>4.4 Tests inexistants ou fabriques</b>", sH2, level=1))
    story.append(p(
        "La section sur les tests du Chapitre 3 presente des resultats qui ne correspondent a aucune "
        "realite mesurable. Il n'existe aucun test automatise reel dans le projet : aucun framework "
        "de test (Jest, Vitest, Playwright Test) n'est configure, aucun fichier de test n'est "
        "present, et aucun script de test n'est defini dans le package.json. Les resultats de "
        "performance presentes dans le Tableau 3.16 sont theoriques et non mesures, comme en "
        "temoigne l'affirmation d'un temps d'authentification de 450ms avec bcrypt alors que "
        "bcrypt n'est pas implemente. L'absence de tests de charge reels et de tests d'integration "
        "automatises est un manque significatif pour un projet de cette envergure."
    ))

    # ════════════════════════════════════════════════════════════════
    # SECTION 5 - SCHEMAS ET ILLUSTRATIONS MANQUANTS
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>5. SCHEMAS ET ILLUSTRATIONS MANQUANTS</b>", sH1))
    story.append(p(
        "Un memoire de Master en informatique devrait contenir un ensemble complet de diagrammes "
        "techniques pour illustrer l'architecture, le comportement et la structure du systeme. "
        "Le Chapitre 3 presente un nombre insuffisant de schemas et illustrations, ce qui rend "
        "la comprehension du systeme difficile et ne permet pas au lecteur de verifier les "
        "descriptions textuelles. Les diagrammes manquants sont essentiels pour une documentation "
        "academique de qualite et leur absence sera probablement remarquee par le jury de soutenance."
    ))

    diagrams = [
        ("Diagramme de cas d'utilisation UML", "Montre les interactions entre les acteurs et le systeme"),
        ("Diagramme de sequence (authentification)", "Detaille le flux d'authentification reel"),
        ("Diagramme de sequence (workflow)", "Illustre les transitions du workflow configurable"),
        ("Diagramme de composants", "Montre l'architecture des composants de l'application"),
        ("Diagramme de deploiement", "Illustre l'infrastructure de deploiement"),
        ("Schema d'architecture multi-tenant", "Essentiel pour comprendre l'isolation des donnees"),
        ("Diagramme ER complet (12+ entites)", "Remplace le MCD incomplet a 5 entites"),
        ("Diagramme d'activite du workflow", "Montre le flux dynamique des documents"),
        ("Diagramme de navigation/interface", "Illustre la structure des ecrans"),
    ]
    diag_data = [
        [Paragraph('<b>N</b>', sTableHeader),
         Paragraph('<b>Diagramme manquant</b>', sTableHeader),
         Paragraph('<b>Justification</b>', sTableHeader)]
    ]
    for i, (name, just) in enumerate(diagrams, 1):
        diag_data.append([
            Paragraph(str(i), sTableCellC),
            Paragraph(name, sTableCell),
            Paragraph(just, sTableCell)
        ])
    col_w = [AVAILABLE_WIDTH * 0.06, AVAILABLE_WIDTH * 0.40, AVAILABLE_WIDTH * 0.54]
    story.extend(make_table(diag_data, col_w, "Tableau 5.1 - Diagrammes manquants"))

    # ════════════════════════════════════════════════════════════════
    # SECTION 6 - CAPTURES D'ECRAN
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>6. CAPTURES D'ECRAN A AJOUTER</b>", sH1))
    story.append(p(
        "Les captures d'ecran constituent des preuves visuelles irremplacables dans un memoire "
        "d'informatique. Elles permettent au lecteur de verifier que les fonctionnalites decrites "
        "existent reellement et de apprecier la qualite de l'interface utilisateur. Le Chapitre 3 "
        "manque cruellement de captures d'ecran, en particulier pour les fonctionnalites les plus "
        "impressionnantes de l'application. L'ajout de captures d'ecran pour les elements suivants "
        "renforcerait considerablement la credibilite du memoire et permettrait de documenter "
        "adequatement la richesse fonctionnelle du projet."
    ))

    screenshots = [
        "6 dashboards specialises (Universitaire, Hospitalier, Entreprise, Gouvernemental, PME, Cabinet juridique)",
        "Panneau Super Admin (dashboard, organisations, modules, analytics, billing)",
        "Page d'inscription et d'authentification",
        "Systeme de notifications en temps reel",
        "Gestion des modules (activation/desactivation par organisation)",
        "Workflow builder (configuration des transitions)",
        "Theme sombre de l'interface utilisateur",
        "Page de parametres systeme",
    ]
    for s in screenshots:
        story.append(bullet(s))
    story.append(Spacer(1, 8))

    # ════════════════════════════════════════════════════════════════
    # SECTION 7 - INCOHERENCES AVEC LES CHAPITRES PRECEDENTS
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>7. INCOHERENCES AVEC LES CHAPITRES PRECEDENTS</b>", sH1))

    story.append(add_heading("<b>7.1 Avec le Chapitre 1</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 1 mentionne l'utilisation de la methode MERISE pour la conception du systeme. "
        "Le Chapitre 3 utilise effectivement MERISE mais de maniere incomplete, avec un MCD qui ne "
        "contient que 5 entites sur les 12+ necessaires. Le Chapitre 1 mentionne egalement "
        "l'utilisation d'UML pour la modelisation, mais aucun diagramme UML n'est present dans le "
        "Chapitre 3. Par ailleurs, le Chapitre 1 cite les normes ISO 15489-1 et OAIS comme "
        "cadre normatif du projet, mais ces normes ne sont ni mentionnees ni implementees dans "
        "le Chapitre 3, creant une rupture entre les fondements theoriques annonces et la pratique "
        "reelle de l'implementation."
    ))

    story.append(add_heading("<b>7.2 Avec le Chapitre 2</b>", sH2, level=1))
    story.append(p(
        "Le Chapitre 2 planifiait une architecture basee sur Spring Boot + React + PostgreSQL. "
        "Le pivot vers Next.js est documente dans le Chapitre 3, mais les alternatives decrites "
        "dans ce dernier sont egalement inexactes. Le Chapitre 2 planifiait l'utilisation de "
        "Keycloak pour l'authentification et de MinIO pour le stockage de fichiers, mais ces "
        "technologies ne sont ni implementees ni explicitement mentionnees comme abandonnees dans "
        "le Chapitre 3. Enfin, le Chapitre 2 presentait un WBS de 49 jours pour le projet, "
        "mais il n'y a aucune retro-information dans le Chapitre 3 sur le respect effectif de "
        "ce planning, ce qui empeche le lecteur d'apprecier la gestion du projet."
    ))

    incoherence_data = [
        [Paragraph('<b>Chapitre</b>', sTableHeader),
         Paragraph('<b>Element</b>', sTableHeader),
         Paragraph('<b>Announce</b>', sTableHeader),
         Paragraph('<b>Reel (Ch.3)</b>', sTableHeader)],
        [Paragraph('Ch.1', sTableCellC),
         Paragraph('MERISE', sTableCell),
         Paragraph('Utilise', sTableCellC),
         Paragraph('Incomplet (5/12 entites)', sTableCell)],
        [Paragraph('Ch.1', sTableCellC),
         Paragraph('UML', sTableCell),
         Paragraph('Utilise', sTableCellC),
         Paragraph('Aucun diagramme', sTableCell)],
        [Paragraph('Ch.1', sTableCellC),
         Paragraph('ISO 15489-1 / OAIS', sTableCell),
         Paragraph('Cadre normatif', sTableCellC),
         Paragraph('Non mentionne', sTableCell)],
        [Paragraph('Ch.2', sTableCellC),
         Paragraph('Spring Boot + React', sTableCell),
         Paragraph('Stack technique', sTableCellC),
         Paragraph('Pivot vers Next.js', sTableCell)],
        [Paragraph('Ch.2', sTableCellC),
         Paragraph('Keycloak', sTableCell),
         Paragraph('Authentification', sTableCellC),
         Paragraph('Non implemente', sTableCell)],
        [Paragraph('Ch.2', sTableCellC),
         Paragraph('MinIO', sTableCell),
         Paragraph('Stockage fichiers', sTableCellC),
         Paragraph('Non implemente', sTableCell)],
        [Paragraph('Ch.2', sTableCellC),
         Paragraph('WBS 49 jours', sTableCell),
         Paragraph('Planning prevu', sTableCellC),
         Paragraph('Pas de retro-information', sTableCell)],
    ]
    col_w = [AVAILABLE_WIDTH * 0.10, AVAILABLE_WIDTH * 0.22, AVAILABLE_WIDTH * 0.28, AVAILABLE_WIDTH * 0.40]
    story.extend(make_table(incoherence_data, col_w, "Tableau 7.1 - Incoherences inter-chapitres"))

    # ════════════════════════════════════════════════════════════════
    # SECTION 8 - QUESTIONS DE DEFENSE
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>8. ELEMENTS SUSCEPTIBLES DE SOULEVER DES QUESTIONS LORS DE LA DEFENSE</b>", sH1))
    story.append(p(
        "Cette section identifie les questions les plus probables que les membres du jury pourraient "
        "poser lors de la soutenance, basees sur les ecarts identifies dans le present audit. Chaque "
        "question est accompagnee de la reponse factuelle que l'etudiant devrait connaitre, ainsi que "
        "du risque associe si la reponse n'est pas preparee adequatement."
    ))

    questions = [
        ("Vous mentionnez bcrypt - ou est-il implemente ?",
         "Il ne l'est PAS. Le code utilise une comparaison en texte brut.",
         "Critique"),
        ("Pourquoi 5 roles alors que le systeme en a 14 ?",
         "Incoherence entre le memoire et l'implementation reelle.",
         "Critique"),
        ("Comment fonctionne le multi-tenant ?",
         "Pas documente dans le Chapitre 3. Architecture SaaS avec isolation des donnees.",
         "Eleve"),
        ("Montrez-nous les tests automatises",
         "Il n'y en a pas. Aucun framework de test n'est configure.",
         "Critique"),
        ("Comment sont calcules les resultats de performance ?",
         "Ils sont fabriques. Aucun test de performance reel n'a ete effectue.",
         "Critique"),
        ("Ou est la validation Zod ?",
         "Elle n'existe pas. Aucune validation de schema n'est implementee.",
         "Eleve"),
        ("Pourquoi le MCD ne contient que 5 entites ?",
         "Il est incomplet. L'application contient 12+ entites.",
         "Eleve"),
        ("Comment l'upload de fichiers fonctionne-t-il ?",
         "Il n'y a pas d'upload reel. Pas de route /api/upload fonctionnelle documentee.",
         "Modere"),
        ("Quelle est la difference entre V1 et V2 ?",
         "Non clarifie dans le memoire. Relation entre versions non documentee.",
         "Modere"),
        ("Comment le systeme de tokens AEIP fonctionne-t-il ?",
         "Pas documente dans le memoire. Format : AEIP-{PREFIX}-{6CHARCODE}.",
         "Modere"),
    ]

    quest_data = [
        [Paragraph('<b>N</b>', sTableHeader),
         Paragraph('<b>Question potentielle du jury</b>', sTableHeader),
         Paragraph('<b>Reponse factuelle</b>', sTableHeader),
         Paragraph('<b>Risque</b>', sTableHeader)]
    ]
    for i, (q, r, risk) in enumerate(questions, 1):
        risk_color = '#8a4741' if risk == 'Critique' else '#aa8c50' if risk == 'Eleve' else '#4c6680'
        quest_data.append([
            Paragraph(str(i), sTableCellC),
            Paragraph(q, sTableCell),
            Paragraph(r, sTableCell),
            Paragraph(f'<font color="{risk_color}">{risk}</font>', sTableCellC)
        ])
    col_w = [AVAILABLE_WIDTH * 0.06, AVAILABLE_WIDTH * 0.30, AVAILABLE_WIDTH * 0.44, AVAILABLE_WIDTH * 0.20]
    story.extend(make_table(quest_data, col_w, "Tableau 8.1 - Questions probables lors de la defense"))

    # ════════════════════════════════════════════════════════════════
    # SECTION 9 - BIBLIOGRAPHIE
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>9. BIBLIOGRAPHIE ET REFERENCES</b>", sH1))
    story.append(p(
        "Le Chapitre 3 ne contient aucune reference bibliographique, ce qui est un manque "
        "significatif pour un memoire de Master. L'absence de references est d'autant plus "
        "problematique que le chapitre decrit des technologies specifiques (Next.js, Prisma, "
        "NextAuth.js, bcrypt, Zod, SHA-256) dont les versions et les fonctionnalites auraient "
        "du etre citees formellement. De plus, les normes ISO mentionnees dans le Chapitre 1 "
        "(ISO 15489-1, OAIS) ne sont pas reprises dans le Chapitre 3, creant une discontinuite "
        "dans le cadre theorique du memoire."
    ))
    story.append(p("Les references manquantes incluent notamment :"))
    refs = [
        "Documentation officielle de Next.js (versions 14 et 16)",
        "Documentation officielle de Prisma ORM (version 6)",
        "Documentation officielle de NextAuth.js",
        "Norme ISO 15489-1 (Records Management)",
        "Modele de reference OAIS (ISO 14721)",
        "Specification bcrypt (Provos et Mazieres, 1999)",
        "Documentation Zod (validation de schemas TypeScript)",
        "Travaux academiques sur la GED cites en introduction",
    ]
    for r in refs:
        story.append(bullet(r))
    story.append(Spacer(1, 8))

    # ════════════════════════════════════════════════════════════════
    # SECTION 10 - RECOMMANDATIONS
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>10. RECOMMANDATIONS</b>", sH1))

    # 10.1
    story.append(add_heading("<b>10.1 Corrections urgentes (avant soutenance)</b>", sH2, level=1))
    story.append(p(
        "Les corrections suivantes sont considerees comme indispensables et doivent etre effectuees "
        "imperativement avant la soutenance. Leur absence risque de soulever des questions fondamentales "
        "sur l'integrite du travail et la fiabilite des informations presentees."
    ))
    urgent = [
        "Remplacer toutes les mentions de bcrypt par la realite (plaintext + plan de migration bcrypt)",
        "Mettre a jour la matrice RBAC avec les 14 roles reels",
        "Compl&eacute;ter le MCD/MLD/MPD avec les 12+ entites existantes",
        "Corriger les donnees de seed (emails et mots de passe incorrects)",
        "Corriger les methodes HTTP (PATCH vers POST pour les actions)",
        "Mettre a jour la version Next.js (14 vers 16)",
        "Supprimer les affirmations sur SHA-256 et Zod non implementes",
        "Documenter l'architecture multi-tenant SaaS",
    ]
    for i, u in enumerate(urgent, 1):
        story.append(Paragraph(f'<b>{i}.</b> {u}', sBullet))

    # 10.2
    story.append(add_heading("<b>10.2 Ajouts recommandes</b>", sH2, level=1))
    story.append(p(
        "Ces ajouts amelioreraient significativement la qualite du memoire et permettraient de "
        "mieux valoriser le travail reellement accompli, qui est plus impressionnant que ce que "
        "le Chapitre 3 laisse transparaitre."
    ))
    additions = [
        "Ajouter des diagrammes UML (cas d'utilisation, sequence, composants)",
        "Ajouter les captures d'ecran manquantes (6 dashboards, Super Admin, etc.)",
        "Documenter le moteur de modules (15 modules avec dependances)",
        "Documenter le systeme de tokens AEIP",
        "Documenter le panneau Super Admin",
        "Ajouter une section sur les limites identifiees du systeme",
        "Ajouter une section sur les perspectives d'amelioration",
        "Ajouter des references bibliographiques aux technologies utilisees",
    ]
    for i, a in enumerate(additions, 1):
        story.append(Paragraph(f'<b>{i}.</b> {a}', sBullet))

    # 10.3
    story.append(add_heading("<b>10.3 Ameliorations de qualite</b>", sH2, level=1))
    story.append(p(
        "Ces ameliorations renforceraient la qualite technique du projet et la credibilite "
        "des resultats presentes dans le memoire."
    ))
    quality = [
        "Effectuer de vrais tests et mesurer les resultats reels",
        "Implementer bcrypt avant la soutenance pour aligner le code avec le memoire",
        "Ajouter des tests automatises (Jest/Vitest pour l'unite, Playwright pour l'E2E)",
        "Ajouter la validation Zod dans les routes API pour la securite",
    ]
    for i, q in enumerate(quality, 1):
        story.append(Paragraph(f'<b>{i}.</b> {q}', sBullet))

    # ════════════════════════════════════════════════════════════════
    # SECTION 11 - TABLEAU RECAPITULATIF
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>11. TABLEAU RECAPITULATIF DES ECARTS</b>", sH1))
    story.append(p(
        "Le tableau suivant resume l'ensemble des ecarts identifies lors de l'audit, avec leur "
        "categorie, description, severite et statut de correction."
    ))

    ecart_rows = [
        ("EC-01", "Securite", "bcrypt non implemente (comparaison plaintext)", "Critique", "Non corrige"),
        ("EC-02", "Architecture", "Mono-tenant vs multi-tenant SaaS", "Critique", "Non corrige"),
        ("EC-03", "Controle acces", "5 roles vs 14 roles RBAC", "Critique", "Non corrige"),
        ("EC-04", "Tests", "Resultats de tests fabriques", "Critique", "Non corrige"),
        ("EC-05", "MCD/MLD", "5 entites vs 12+ entites", "Critique", "Non corrige"),
        ("EC-06", "Securite", "SHA-256 non implemente", "Eleve", "Non corrige"),
        ("EC-07", "Securite", "Validation Zod non implementee", "Eleve", "Non corrige"),
        ("EC-08", "Donnees", "Identifiants de seed incorrects", "Eleve", "Non corrige"),
        ("EC-09", "API", "Methodes HTTP et routes incorrectes", "Eleve", "Non corrige"),
        ("EC-10", "Interface", "1 dashboard vs 7 dashboards", "Eleve", "Non corrige"),
        ("EC-11", "Technique", "Version Next.js incorrecte (14 vs 16)", "Modere", "Non corrige"),
        ("EC-12", "Reference", "Format reference incorrect (ISIPA-XX vs DOC-timestamp)", "Modere", "Non corrige"),
        ("EC-13", "Architecture", "Middleware vs proxy.ts", "Modere", "Non corrige"),
        ("EC-14", "Documentation", "16+ fonctionnalites non documentees", "Eleve", "Non corrige"),
        ("EC-15", "Schema", "8 diagrammes techniques manquants", "Eleve", "Non corrige"),
        ("EC-16", "Captures", "8+ captures d'ecran manquantes", "Modere", "Non corrige"),
        ("EC-17", "Coherence", "Incoherences avec Chapitre 1 (MERISE, UML, ISO)", "Modere", "Non corrige"),
        ("EC-18", "Coherence", "Incoherences avec Chapitre 2 (Keycloak, MinIO, WBS)", "Modere", "Non corrige"),
        ("EC-19", "Bibliographie", "Aucune reference dans le Chapitre 3", "Eleve", "Non corrige"),
        ("EC-20", "Environnement", "Turbopack, Tailwind 4, Prisma v6 non mentionnes", "Modere", "Non corrige"),
    ]

    recap_data = [
        [Paragraph('<b>ID</b>', sTableHeader),
         Paragraph('<b>Categorie</b>', sTableHeader),
         Paragraph('<b>Description</b>', sTableHeader),
         Paragraph('<b>Severite</b>', sTableHeader),
         Paragraph('<b>Statut</b>', sTableHeader)]
    ]
    for eid, cat, desc, sev, stat in ecart_rows:
        sev_color = '#8a4741' if sev == 'Critique' else '#aa8c50' if sev == 'Eleve' else '#4c6680'
        recap_data.append([
            Paragraph(eid, sTableCellC),
            Paragraph(cat, sTableCell),
            Paragraph(desc, sTableCell),
            Paragraph(f'<font color="{sev_color}">{sev}</font>', sTableCellC),
            Paragraph(stat, sTableCellC)
        ])
    col_w = [AVAILABLE_WIDTH * 0.08, AVAILABLE_WIDTH * 0.14, AVAILABLE_WIDTH * 0.44, AVAILABLE_WIDTH * 0.16, AVAILABLE_WIDTH * 0.18]
    story.extend(make_table(recap_data, col_w, "Tableau 11.1 - Recapitulatif des ecarts"))

    # ════════════════════════════════════════════════════════════════
    # SECTION 12 - CONCLUSION
    # ════════════════════════════════════════════════════════════════
    story.extend(add_major_section("<b>12. CONCLUSION</b>", sH1))
    story.append(p(
        "L'audit de conformite entre le Chapitre III du memoire de Master et l'application GED-ISIPA "
        "reellement deployee revele des ecarts significatifs qui necessitent une attention urgente. "
        "Avec un taux de completude estime a 45%, 12 ecarts majeurs et 18 ecarts mineurs identifies, "
        "le chapitre en son etat actuel ne presente pas une image fidele du travail reellement accompli. "
        "Les informations inexactes les plus graves concernent la securite (affirmation de l'utilisation "
        "de bcrypt alors que les mots de passe sont compares en texte brut), l'architecture (description "
        "d'un systeme mono-tenant alors que l'application est multi-tenant SaaS), et les resultats de "
        "tests (fabrication de resultats de performance non mesures)."
    ))
    story.append(p(
        "Il est toutefois important de noter que l'application reelle est bien plus riche et plus "
        "impressionnante que ce que le Chapitre 3 laisse transpara&icirc;tre. L'architecture multi-tenant, "
        "les 6 dashboards specialises, le moteur de modules, le systeme de tokens AEIP, et le panneau "
        "Super Admin sont des fonctionnalites de haut niveau qui valorisent considerablement le projet. "
        "Le probleme n'est pas que l'application soit de mauvaise qualite, mais que le memoire ne la "
        "decrit pas correctement, omettant ses atouts les plus significatifs tout en affirmant des "
        "fonctionnalites qui n'existent pas."
    ))
    story.append(p(
        "Avec les corrections recommandees dans la section 10 de ce rapport, le Chapitre 3 peut "
        "atteindre le niveau de qualite attendu pour un memoire de Master. La mise a jour du MCD, "
        "l'ajout des diagrammes UML, la correction des informations inexactes, et l'ajout de captures "
        "d'ecran demonstratives permettront de presenter un travail fidele a la realite et digne "
        "d'une soutenance de Master. L'etudiant est vivement encourage a entreprendre ces corrections "
        "avant la soutenance afin d'eviter les questions embarrassantes identifiees dans la section 8 "
        "et de valoriser pleinement le travail substantiel qui a ete reellement accompli."
    ))
    story.append(Spacer(1, 24))
    story.append(HRFlowable(width="60%", thickness=1, color=ACCENT, spaceAfter=8, spaceBefore=8, hAlign='CENTER'))
    story.append(p(
        "<i>Fin du rapport d'audit - Document genere automatiquement - Confidentiel</i>", sCaption
    ))

    return story


# ━━ MAIN ━━
def main():
    print("=== Generation du rapport d'audit academique ===")

    # Step 1: Write cover HTML
    print("[1/5] Ecriture du HTML de couverture...")
    write_cover_html()

    # Step 2: Validate cover HTML
    print("[2/5] Validation du HTML de couverture...")
    try:
        result = subprocess.run(
            ['node', os.path.join(PDF_SKILL_DIR, 'scripts', 'cover_validate.js'), COVER_HTML],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            print(f"  WARNING: Cover validation found issues: {result.stdout}")
        else:
            print("  Cover validation PASSED")
    except Exception as e:
        print(f"  WARNING: Cover validation skipped: {e}")

    # Step 3: Render cover PDF
    print("[3/5] Rendu de la couverture via html2poster.js...")
    try:
        subprocess.run([
            'node', os.path.join(PDF_SKILL_DIR, 'scripts', 'html2poster.js'),
            COVER_HTML, '--output', COVER_PDF, '--width', '794px'
        ], check=True, capture_output=True, text=True, timeout=60)
        print(f"  Cover PDF generated: {COVER_PDF}")
    except subprocess.CalledProcessError as e:
        print(f"  ERROR rendering cover: {e.stderr}")
        sys.exit(1)

    # Step 4: Build body PDF via ReportLab
    print("[4/5] Generation du corps du document via ReportLab...")
    doc = TocDocTemplate(
        BODY_PDF,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title="Rapport d'Audit Academique - Chapitre III - GED-ISIPA",
        author='Z.ai',
        creator='Z.ai',
        subject='Audit de conformite entre le memoire et l\'application deployee'
    )

    story = build_story()

    # We need multiBuild for TOC
    doc.multiBuild(story, onLaterPages=header_footer, onFirstPage=header_footer_toc)
    print(f"  Body PDF generated: {BODY_PDF}")

    # Step 5: Merge cover + body
    print("[5/5] Fusion couverture + corps...")
    from pypdf import PdfReader, PdfWriter, Transformation

    A4_W, A4_H = 595.28, 841.89

    def normalize_page_to_a4(page):
        box = page.mediabox
        w, h = float(box.width), float(box.height)
        if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
            sx, sy = A4_W / w, A4_H / h
            page.add_transformation(Transformation().scale(sx=sx, sy=sy))
            page.mediabox.lower_left = (0, 0)
            page.mediabox.upper_right = (A4_W, A4_H)
        return page

    writer = PdfWriter()
    # Cover as page 1
    cover_page = PdfReader(COVER_PDF).pages[0]
    writer.add_page(normalize_page_to_a4(cover_page))
    # Body pages follow
    for page in PdfReader(BODY_PDF).pages:
        writer.add_page(normalize_page_to_a4(page))

    writer.add_metadata({
        '/Title': "Rapport d'Audit Academique - Chapitre III - GED-ISIPA",
        '/Author': 'Z.ai',
        '/Creator': 'Z.ai',
        '/Subject': 'Audit de conformite entre le memoire et l\'application deployee'
    })

    with open(FINAL_PDF, 'wb') as f:
        writer.write(f)

    # Get page count
    total_pages = len(PdfReader(FINAL_PDF).pages)

    # Cleanup temp files
    for tmp in [BODY_PDF, COVER_PDF, COVER_HTML]:
        try:
            os.remove(tmp)
        except:
            pass

    file_size = os.path.getsize(FINAL_PDF)
    print(f"\n=== Rapport genere avec succes ===")
    print(f"  Fichier: {FINAL_PDF}")
    print(f"  Taille: {file_size / 1024:.1f} Ko")
    print(f"  Pages: {total_pages}")


if __name__ == '__main__':
    main()
